<?php

/* This file is part of Jeedom.
 *
 * Jeedom is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Jeedom is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jeedom. If not, see <http://www.gnu.org/licenses/>.
 */

global $listCmdtelecfree;
$listCmdtelecfree = array(
    array(
        'name' => 'Allumer-Eteindre',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'power',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Allumer ou eteindre',
		'group' => 'basic',
		'icon' => 'fa fa-power-off',
    ),
    array(
        'name' => '0',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '0',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 0',
        'group' => 'basic',
    ),
    array(
        'name' => '1',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '1',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 1',
        'group' => 'basic',
    ),
    array(
        'name' => '2',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '2',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 2',
        'group' => 'basic',
    ),
    array(
        'name' => '3',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '3',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 3',
        'group' => 'basic',
    ),
    array(
        'name' => '4',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '4',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 4',
        'group' => 'basic',
    ),
    array(
        'name' => '5',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '5',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 5',
        'group' => 'basic',
    ),
    array(
        'name' => '6',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '6',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 6',
        'group' => 'basic',
    ),
    array(
        'name' => '7',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '7',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 7',
        'group' => 'basic',
    ),
    array(
        'name' => '8',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '8',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 8',
        'group' => 'basic',
    ),
    array(
        'name' => '9',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '9',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton 9',
        'group' => 'basic',
    ),
    array(
        'name' => 'Haut',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'up',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton haut',
        'group' => 'basic',
		'icon' => 'fa fa-arrow-up',
    ),
    array(
        'name' => 'Bas',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'down',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton bas',
        'group' => 'basic',
		'icon' => 'fa fa-arrow-down',
    ),
    array(
        'name' => 'Gauche',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'left',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton gauche',
        'group' => 'basic',
		'icon' => 'fa fa-arrow-left',
    ),
    array(
        'name' => 'Droite',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'right',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton droit',
        'group' => 'basic',
		'icon' => 'fa fa-arrow-right',
    ),
    array(
        'name' => 'OK',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'ok',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton OK',
        'group' => 'basic',
    ),
    array(
        'name' => 'Home',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'home',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton home',
        'group' => 'basic',
		'icon' => 'fa fa-home',
    ),
    array(
        'name' => 'Vol+',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'vol_inc',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Volume haut',
        'group' => 'basic',
		'icon' => 'fa fa-volume-up',
    ),
	array(
        'name' => 'Vol',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'vol_inc',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Volume haut',
        'group' => 'basic',
    ),
    array(
        'name' => 'Vol-',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'vol_dec',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Volume bas',
        'group' => 'basic',
		'icon' => 'fa fa-volume-down',
    ),
    array(
        'name' => 'Muet',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'mute',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Muet on-off',
        'group' => 'basic',
		'icon' => 'fa fa-volume-off',
    ),
    array(
        'name' => 'Chaine+',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'prgm_inc',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 0haut',
        'group' => 'basic',
		'icon' => 'fa fa-plus',
    ),
	array(
        'name' => 'Chaine',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'prgm_inc',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 0haut',
        'group' => 'basic',
    ),
    array(
        'name' => 'Chaine-',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'prgm_dec',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 0bas',
        'group' => 'basic',
		'icon' => 'fa fa-minus',
    ),
    array(
        'name' => 'Recherche',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'blue',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton bleu',
        'group' => 'basic',
    ),
    array(
        'name' => 'Menu',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'green',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton vert',
        'group' => 'basic',
    ),
    array(
        'name' => 'Retour',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'red',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton rouge',
        'group' => 'basic',
    ),
    array(
        'name' => 'Info',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'yellow',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton jaune',
        'group' => 'basic',
    ),
    array(
        'name' => 'Play',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'play',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton lecture',
        'group' => 'basic',
		'icon' => 'fa fa-play',
    ),
    array(
        'name' => 'Pause',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'play',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton pause',
        'group' => 'basic',
		'icon' => 'fa fa-pause',
    ),
    array(
        'name' => 'Avance rapide',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'fwd',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton avance rapide',
        'group' => 'basic',
		'icon' => 'fa fa-forward',
    ),
    array(
        'name' => 'Retour rapide',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'bwd',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton retour rapide',
        'group' => 'basic',
		'icon' => 'fa fa-backward',
    ),
    array(
        'name' => 'Enregistrer',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'rec',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Bouton record',
        'group' => 'basic',
		'icon' => 'fa fa-circle',
    ),
	array(
        'name' => 'Univers tv',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '981',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers TV',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Univers replay',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '982',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers replay',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Univers videos',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '983',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers videos',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Univers radios',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '984',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers radios',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Univers musiques',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '985',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers musiques',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Univers disques',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '986',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers disques',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Univers programmes',
        'configuration' => array(
            'request' => 'key',
            'parameters' => '987',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Univers programmes',
        'group' => 'raccourcis',
    ),
	array(
        'name' => 'Chaine 001',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_001',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 001',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 002',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_002',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 002',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 003',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_003',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 003',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 004',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_004',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 004',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 005',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_005',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 005',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 006',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_006',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 006',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 007',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_007',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 007',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 008',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_008',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 008',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 009',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_009',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 009',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 010',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_010',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 010',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 011',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_011',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 011',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 012',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_012',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 012',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 013',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_013',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 013',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 014',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_014',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 014',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 015',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_015',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => true,
        'description' => 'Chaine 015',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 016',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_016',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 016',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 017',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_017',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 017',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 018',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_018',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 018',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 019',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_019',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 019',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 020',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_020',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 020',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 021',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_021',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 021',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 022',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_022',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 022',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 023',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_023',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 023',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 024',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_024',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 024',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 025',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_025',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 025',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 026',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_026',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 026',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 027',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_027',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 027',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 028',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_028',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 028',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 031',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_031',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 031',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 032',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_032',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 032',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 039',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_039',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 039',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 048',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_048',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 048',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine 143',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaine_143',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine 143',
        'group' => 'chaines',
    ),
	array(
        'name' => 'Chaine perso 1',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 1',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 2',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 2',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 3',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 3',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 4',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 4',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 5',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 5',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 6',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 6',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 7',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 7',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 8',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 8',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 9',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 9',
        'group' => 'chainesperso',
		'icon' => '',
    ),
	array(
        'name' => 'Chaine perso 10',
        'configuration' => array(
            'request' => 'key',
            'parameters' => 'chaineperso_000',
        ),
        'type' => 'action',
        'subType' => 'other',
		'isVisible' => false,
        'description' => 'Chaine perso 10',
        'group' => 'chainesperso',
		'icon' => '',
    )
);
?>
